name: CI

on:
  push:
    branches:
      - 15Feb-ci-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Build Docker image
        run: docker build -t <DOCKER_HUB_USERNAME>/<IMAGE_NAME>:latest .

      - name: Push Docker image to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push <DOCKER_HUB_USERNAME>/<IMAGE_NAME>:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Analyze code with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          githubToken: ${{ secrets.GIT_HUB_TOKEN }}
          organization: ${{ secrets.SONAR_ORGANIZATION }}
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
